name: Bug Report
description: Report incorrect or unexpected behaviour from the bot.
labels: bug
assignees: thehackerboi69github
body:
  - type: markdown
    attributes:
      value: For questions, please visit the Discord server at https://discord.gg/QrsUxMPcSu
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: |
        Please describe the issue as detailed as possible.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files into it.
      placeholder: |
        Steps to reproduce:
        1. do something
        2. do something else
        3. observe behavior
        4. get an error
    validations:
      required: true
  - type: textarea
    id: errorlogs
    attributes:
      label: Error logs
      description: |
        Include error logs if you're running a fork.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files into it.
      render: txt
      placeholder: |
        TypeError: Cannot read properties of undefined (reading 'foo') (dist/index.js 6:9)
  - type: input
    id: node-version
    attributes:
      label: Node.js version
      description: |
        Please include your Node.js version here if you're running a fork.
        You can get your Node.js version by running `node --version`.
        If there is an issue with the typings, please also include your TypeScript version here (`npm list typescript`)
      placeholder: v18.x.x
